sonar.projectKey=uk.gov.justice.cpp.ui:ui-core
sonar.projectName=@cpp:ui.core

sonar.projectDescription=CPP UI Core Library
sonar.links.homepage=https://github.com/hmcts/cpp-ui-core
#sonar.links.ci=
#sonar.links.issue=
sonar.links.scm=https://github.com/hmcts/cpp-ui-core
sonar.links.scm_dev=git@github.com:hmcts/cpp-ui-core.git

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=tests.bundle.ts,build/**/*,node_modules/**/*,release/**/*, dist/**/*,documentation/**, projects/**/*, scripts/**/*

# Optional
#sonar.tests=test/**/*.js
# Tests
sonar.dependencyCheck.reportPath=build/dependency-check/dependency-check-report.xml
sonar.dependencyCheck.htmlReportPath=build/dependency-check/dependency-check-report.html
#sonar.javascript.lcov.reportPaths=build/coverage/jest/lcov.info
sonar.typescript.exclusions=**/node_modules/**,**/bower_components/**,build/**,dist/**,documentation/**
sonar.typescript.lcov.reportPaths=build/coverage/jest/lcov.info
# SonarQube 7.2+ https://docs.sonarqube.org/display/PLUG/Importing+TSLint+issues+for+TypeScript+files
sonar.typescript.tslint.jsonReportPaths=build/lint/tslint.json
